<?php
/**
 * @file
 * Code for the Ding Blog feature.
 */

include_once 'ding_blog.features.inc';

/**
 * Implements hook_secure_permissions().
 */
function ding_blog_secure_permissions($role) {
  $permissions = array(
    'staff' => array(
      'access media browser',
      'create files',
      'edit own image files',
      'delete own image files',
      'download own image files',
      'edit own video files',
      'delete own video files',
      'download own video files',
      'edit own audio files',
      'delete own audio files',
      'download own audio files',
      'edit own document files',
      'delete own document files',
      'download own document files',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function ding_blog_theme_registry_alter(&$theme_registry) {
  // Defined path to the current module.
  $path = drupal_get_path('module', 'ding_blog');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ding_blog_preprocess_node(&$variables) {
  $function = 'ding_blog_preprocess__node__blog';
  if (function_exists($function)) {
    call_user_func_array($function, array(&$variables));
  }
}

/**
 * Ding blog.
 */
function ding_blog_preprocess__node__blog(&$variables) {
  $variables['blog_submitted'] = format_date($variables['created'], 'ding_date_only_version2');

  switch ($variables['view_mode']) {
    case 'teaser':
      if (!empty($variables['field_ding_blog_list_image'][0]['uri'])) {
        // Get image url to use as background image.
        $uri = $variables['field_ding_blog_list_image'][0]['uri'];

        $image_title = $variables['field_ding_blog_list_image'][0]['title'];

        // If in view with large first teaser and first in view.
        $current_view = $variables['view']->current_display;
        $views_with_large_first = array('ding_blog_frontpage_list');
        if (in_array($current_view, $views_with_large_first) && $variables['view']->result[0]->nid == $variables['nid']) {
          $img_url = image_style_url('ding_panorama_list_large_wide', $uri);
          $variables['classes_array'][] = 'ding-blog-highlighted';
        }
        else {
          $img_url = image_style_url('ding_panorama_list_large', $uri);
        }
        if (!empty($image_title)) {
          $variables['blog_teaser_image'] = '<div class="ding-blog-list-image background-image-styling-16-9" style="background-image:url(' . $img_url . ')" title="' . $image_title . '"></div>';
        }
        else {
          $variables['blog_teaser_image'] = '<div class="ding-blog-list-image background-image-styling-16-9" style="background-image:url(' . $img_url . ')"></div>';
        }
      }
      else {
        $variables['blog_teaser_image'] = '<div class="ding-blog-list-image background-image-styling-16-9"></div>';
      }
      break;
  }
}
