<?php
/**
 * @file
 * Code for the Ding Blog feature.
 */

include_once 'ding_blog.features.inc';

/**
 * Implements hook_secure_permissions().
 */
function ding_blog_secure_permissions($role) {
  $permissions = array(
    'staff' => array(
      'access media browser',
      'create files',
      'edit own image files',
      'delete own image files',
      'download own image files',
      'edit own video files',
      'delete own video files',
      'download own video files',
      'edit own audio files',
      'delete own audio files',
      'download own audio files',
      'edit own document files',
      'delete own document files',
      'download own document files',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}
